start:
  - run: ./scripts/start.sh
  - on: windows
    run: scripts\start.cmd
stop:
  - run: ./scripts/stop.sh
  - on: windows
    run: scripts\stop.cmd

auto_start: true

env:
  - DEBUG=false

stdout_log: debug
stderr_log: warn
